plugins:
  discourse_frotz_enabled:
    default: true
    client: false
  frotz_permitted_in_private_messages:
    default: false
    client: false
  frotz_permitted_all_categories:
    default: true
    client: false
  frotz_permitted_categories:
    client: false
    default: ''
    type: category_list
    list_type: "compact"
  frotz_stories:
    client: false
    type: list
    default: "The Hitchhiker's Guide to the Galaxy,hhgg.z3|Zork 1,zork1.z5"
  frotz_bot_user:
    client: false
    type: username
    default: -5
  frotz_dumb_executable_directory:
    client: false
    default: "frotz"
  frotz_saves_directory:
    client: false
    default: "frotz/savegames"
  frotz_story_files_directory:
    client: false
    default: "frotz/stories"
