plugins:
  chatbot_enabled:
    default: true
    client: false
  chatbot_permitted_in_private_messages:
    default: false
    client: false
  chatbot_permitted_all_categories:
    default: true
    client: false
  chatbot_permitted_categories:
    client: false
    default: ''
    type: category_list
    list_type: "compact"
  chatbot_max_look_behind:
    default: 5
    client: false
  chatbot_base_url:
    client: false
    default: "https://api.openai.com/v1/completions"
  chatbot_open_ai_model:
    client: false
    default: "text-davinci-003"
  chatbot_open_ai_token:
    client: false
    default: ''
  chatbot_request_temperature:
    client: false
    default: 0
  chatbot_max_response_tokens:
    client: false
    default: 200
  chatbot_bot_user:
    client: true
    type: username
    default: aibot
