plugins:
  openai_bot_enabled:
    default: true
    client: false
  openai_bot_permitted_in_private_messages:
    default: false
    client: false
  openai_bot_permitted_all_categories:
    default: true
    client: false
  openai_bot_permitted_categories:
    client: false
    default: ''
    type: category_list
    list_type: "compact"
  openai_bot_max_look_behind:
    default: 5
    client: false
  openai_bot_base_url:
    client: false
    default: "https://api.openai.com/v1/completions"
  openai_bot_open_ai_model:
    client: false
    default: "text-davinci-003"
  openai_bot_open_ai_token:
    client: false
    default: ''
  openai_bot_request_temperature:
    client: false
    default: 0
  openai_bot_max_response_tokens:
    client: false
    default: 200
  openai_bot_bot_user:
    client: false
    type: username
    default: -5
