plugins:
  discourse_openai_bot_enabled:
    default: true
    client: false
  openai_bot_permitted_in_private_messages:
    default: false
    client: false
  openai_bot_permitted_all_categories:
    default: true
    client: false
  openai_bot_permitted_categories:
    client: false
    default: ''
    type: category_list
    list_type: "compact"
  openai_bot_base_url:
    client: false
    default: "https://api.openai.com/v1/completions"
  openai_bot_request_model:
    client: false
    default: "text-davinci-003"
  openai_bot_api_key:
    client: false
    default: ''
  openai_bot_request_temperature:
    client: false
    default: 0
  openai_bot_request_max_tokens:
    client: false
    default: 10
  openai_bot_bot_user:
    client: false
    type: username
    default: -5
  openai_bot_text_stream_timeout:
    client: false
    default: 0.5
    type: number
